# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='T\xedtulo de la entrada')),
                ('body', models.TextField()),
                ('tags', models.CharField(max_length=300, verbose_name='Contenido de la entrada')),
                ('show_image', models.BooleanField(default=True, verbose_name='Mostrar imagen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='media')),
            ],
        ),
    ]
